[platformio]
default_envs = web_server

[env]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_dtr = 0
monitor_rts = 0

[env:web_server]
build_src_filter = +<*.cpp> -<Serial-control.cpp>
lib_deps =
  pu2clr/PU2CLR Si4735 @ ^2.1.8
  https://github.com/me-no-dev/ESPAsyncTCP.git
  https://github.com/me-no-dev/ESPAsyncWebServer.git

[env:serial_control]
build_src_filter = +<*.cpp> -<main.cpp>
lib_deps =
  pu2clr/PU2CLR Si4735 @ ^2.1.8
[env:unified]
build_src_filter = +<*.cpp> -<main.cpp> -<Serial-control.cpp>
lib_deps =
  pu2clr/PU2CLR Si4735 @ ^2.1.8
  https://github.com/me-no-dev/ESPAsyncTCP.git
  https://github.com/me-no-dev/ESPAsyncWebServer.git